-- Generated by scripts/generate-outreach-seed.mjs. Do not edit by hand.
-- Apply: npx wrangler d1 execute tourproshop-outreach --remote --file=migrations/0002_outreach_seed.sql

INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('andrew-kipper', 'Andrew Kipper', 'Excel Sports', 'andrew@excelsm.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('brent-hamilton', 'Brent Hamilton', 'Win Sports Group', 'bhamilton@winsg.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('brett-augenstein', 'Brett Augenstein', 'GSE', 'baugenstein@gseworldwide.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('brett-falkoff', 'Brett Falkoff', 'GSE', 'bfalkoff@gseworldwide.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('brittany-elsner', 'Brittany Elsner', 'Excel Sports', 'belsner@excelsm.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('bud-martin', 'Bud Martin', 'The Team', 'bmartin@the.team', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('charlie-danielson', 'Charlie Danielson', 'Pro Advisory Group', 'charliegolf24@gmail.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('gao-ya-chen', 'Gao-Ya Chen', 'Status Management LLC', 'gchen@statusmanagement.llc', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('ian-keenan', 'Ian Keenan', 'The Team', 'ikeenan@the.team', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('jeremy-elliott', 'Jeremy Elliott', 'SPORTFIVE', 'jeremy.elliott@sportfive.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('jon-heaton', 'Jon Heaton', 'Excel Sports', 'jheaton@excelsm.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('kelly-presley', 'Kelly Presley', 'Excel Sports', 'kpresley@excelsm.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('kevin-lynch', 'Kevin Lynch', 'RockEmpire', 'kevin.lynch@rockempiresports.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('lance-young', 'Lance Young', 'Excel Sports', 'lyoung@excelsm.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('preston-valder', 'Preston Valder', 'Nexus Sports', 'preston@nexus-sports.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('rob-mougey', 'Rob Mougey', 'The Familie', 'rob@thefamilie.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('sean-riley', 'Sean Riley', 'SPORTFIVE', 'sean.riley@sportfive.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('tommy-riehle', 'Tommy Riehle', 'SPORTFIVE', 'thomas.riehle@sportfive.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('walker-huddy', 'Walker Huddy', 'Hambric Sports', 'whuddy@hambricsports.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('brad-buffoni', 'Brad Buffoni', 'The Team', 'bbuffoni@the.team', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('chris-mullhaupt', 'Chris Mullhaupt', 'The Team', 'cmullhaupt@the.team', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('derek-bohlen', 'Derek Bohlen', 'Range Sports', 'dbohlen@rangemp.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('lynn-roach-jr', 'Lynn Roach, Jr.', 'Players Group Management', 'lroach@playersgroupmanagement.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('moon-jo', 'Moon Jo', 'Moon Jo', 'mjgolf@atsports.co.kr', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('richard-zulick', 'Richard Zulick', 'Noble Sports Group-NGMG LLC', 'richard@noblesportsgroup.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('rob-goulet', 'Rob Goulet', 'Entertainment Sports Partners', 'rob@entertainmentsports.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('robert-turner', 'Robert Turner', 'Turner Communications Int''l, Inc.', 'tcibobturner@aol.com', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('terry-reilly', 'Terry Reilly', 'The Team', 'treilly@the.team', '/agents');
INSERT OR IGNORE INTO outreach_links (slug, agent_name, agency, email, target_url) VALUES ('mike-creasy', 'Mike Creasy', 'GSE', 'mcreasy@gseworldwide.com', '/agents');
